### ISSUE TITLE
invite link for slack

### ISSUE THREAD

**Issue by thienpow** [Cezerin2/cezerin2.github.io#1]
please create invite link for slack, thanks.

https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link-

**Comment by vamcart** [comment]
> please create invite link for slack, thanks.
> 
> https://get.slack.help/hc/en-us/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link-

Hi!

Try this link: https://join.slack.com/t/cezerin2/shared_invite/enQtNTE5NzYxMzA5ODc5LTVkZjM4ODUwMmNlMmMyZTkxYjg5N2QxZmQ5NjA1NTg3OWM2ZjU1NzVmNWM0N2E3ZmJjM2Q3MjQ5OGFmNTBmYjg
