### ISSUE TITLE
Documentation for Store, Admin & Client

### ISSUE THREAD

**Issue by hung1806vn** [Cezerin2/cezerin2.github.io#3]
I really need setup guide for separating store & client

**Comment by ngoyal16** [comment]
@hung1806vn we have documented some process of installation at https://cezerin.org/docs/#/. more coming soon

**Comment by hung1806vn** [comment]
Amazing, thanks for your effort.

**Comment by vamcart** [comment]
Docs updated - https://cezerin.org/docs/#/using-source-code
Youtube video added.
